disable linux + retry on brew install

diff --git a/.github/workflows/release.yml b/.github/workflows/release.yml
--- a/.github/workflows/release.yml
+++ b/.github/workflows/release.yml
@@ -12,7 +12,8 @@ jobs:
     name: Build and Release
     strategy:
       matrix:
-        os: [macos-latest, ubuntu-latest]
+#        os: [macos-latest, ubuntu-latest]
+        os: [macos-latest]
 
     runs-on: ${{ matrix.os }}
 
@@ -23,7 +24,21 @@ jobs:
       - name: Set up dependencies (macOS)
         if: ${{ matrix.os == 'macos-latest' }}
         run: |
-          brew update
+          attempts=0
+          max_attempts=3
+          while [ $attempts -lt $max_attempts ]; do
+            brew update --auto && brew upgrade
+            if [ $? -eq 0 ]; then
+              break
+            fi
+            echo "Homebrew install failed. Retrying in 5 seconds..."
+            sleep 5
+            attempts=$((attempts+1))
+          done
+          if [ $attempts -eq $max_attempts ]; then
+            echo "Homebrew install failed after multiple retries."
+            exit 1
+          fi
           brew install sfml
           brew install nlohmann_json
 
